const list = [
  [
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: {
                job: "Pickup",
                details: "food",
                location: "Toronto",
                length: 2,
              },
            },
            {
              id: 2,
              task: {
                job: "Pickup",
                details: "food",
                location: "Toronto",
                length: 2,
              },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 7,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 8,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 9,
              task: {
                job: "Dropoff",
                details: "kids",
                location: "Toronto",
                length: 1,
              },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: {
                job: "Pickup",
                details: "coffee",
                location: "Ottawa",
                length: 2,
              },
            },
            {
              id: 9,
              task: {
                job: "Pickup",
                details: "coffee",
                location: "Ottawa",
                length: 2,
              },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 14,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 15,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 16,
              task: {
                job: "Dropoff",
                details: "stuff",
                location: "Kingston",
                length: 1,
              },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            {
              id: 9,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 14,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 15,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 16,
              task: { job: "Dropoff", details: "stuff", location: "Kingston" },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            {
              id: 9,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 14,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 15,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 16,
              task: { job: "Dropoff", details: "stuff", location: "Kingston" },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
  ],
  [
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: {
                job: "Pickup",
                details: "PERSON 2",
                location: "Toronto",
                length: 2,
              },
            },
            {
              id: 2,
              task: {
                job: "Pickup",
                details: "PERSON 2",
                location: "Toronto",
                length: 2,
              },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 7,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 8,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 9,
              task: {
                job: "Dropoff",
                details: "kids",
                location: "Toronto",
                length: 1,
              },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: {
                job: "Pickup",
                details: "coffee",
                location: "Ottawa",
                length: 2,
              },
            },
            {
              id: 9,
              task: {
                job: "Pickup",
                details: "coffee",
                location: "Ottawa",
                length: 2,
              },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 14,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 15,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 16,
              task: {
                job: "Dropoff",
                details: "stuff",
                location: "Kingston",
                length: 1,
              },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            {
              id: 9,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 14,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 15,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 16,
              task: { job: "Dropoff", details: "stuff", location: "Kingston" },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            {
              id: 9,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 14,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 15,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 16,
              task: { job: "Dropoff", details: "stuff", location: "Kingston" },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
  ],
  [
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: {
                job: "Pickup",
                details: "P3",
                location: "Toronto",
                length: 2,
              },
            },
            {
              id: 2,
              task: {
                job: "Pickup",
                details: "P3",
                location: "Toronto",
                length: 2,
              },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 7,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 8,
              task: {
                job: "Other",
                details: "coffee",
                location: "Toronto",
                length: 3,
              },
            },
            {
              id: 9,
              task: {
                job: "Dropoff",
                details: "kids",
                location: "Toronto",
                length: 1,
              },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: {
                job: "Pickup",
                details: "coffee",
                location: "Ottawa",
                length: 2,
              },
            },
            {
              id: 9,
              task: {
                job: "Pickup",
                details: "coffee",
                location: "Ottawa",
                length: 2,
              },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 14,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 15,
              task: {
                job: "Pickup",
                details: "kids",
                location: "Ottawa",
                length: 3,
              },
            },
            {
              id: 16,
              task: {
                job: "Dropoff",
                details: "stuff",
                location: "Kingston",
                length: 1,
              },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            {
              id: 9,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 14,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 15,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 16,
              task: { job: "Dropoff", details: "stuff", location: "Kingston" },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
    {
      id: 1,
      name: "Week 1",
      weekdays: [
        {
          id: 1,
          name: "Sunday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 2,
          name: "Monday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            {
              id: 8,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            {
              id: 9,
              task: { job: "Pickup", details: "coffee", location: "Ottawa" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            {
              id: 13,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 14,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 15,
              task: { job: "Pickup", details: "kids", location: "Ottawa" },
            },
            {
              id: 16,
              task: { job: "Dropoff", details: "stuff", location: "Kingston" },
            },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 3,
          name: "Tuesday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 4,
          name: "Wednesday",
          schedule: [
            { id: 0, task: [] },
            {
              id: 1,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            {
              id: 2,
              task: { job: "Pickup", details: "food", location: "Toronto" },
            },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            {
              id: 6,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 7,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 8,
              task: { job: "Other", details: "coffee", location: "Toronto" },
            },
            {
              id: 9,
              task: { job: "Dropoff", details: "kids", location: "Toronto" },
            },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 5,
          name: "Thursday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 6,
          name: "Friday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
        {
          id: 7,
          name: "Saturday",
          schedule: [
            { id: 0, task: [] },
            { id: 1, task: [] },
            { id: 2, task: [] },
            { id: 3, task: [] },
            { id: 4, task: [] },
            { id: 5, task: [] },
            { id: 6, task: [] },
            { id: 7, task: [] },
            { id: 8, task: [] },
            { id: 9, task: [] },
            { id: 10, task: [] },
            { id: 11, task: [] },
            { id: 12, task: [] },
            { id: 13, task: [] },
            { id: 14, task: [] },
            { id: 15, task: [] },
            { id: 16, task: [] },
            { id: 17, task: [] },
            { id: 18, task: [] },
            { id: 19, task: [] },
            { id: 20, task: [] },
            { id: 21, task: [] },
            { id: 22, task: [] },
            { id: 23, task: [] },
          ],
        },
      ],
    },
  ],
];
