const schedule = [
  {
    id: 51,
    name: "Week 52",
    weekdays: [
      {
        id: 1,
        name: "Sunday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 2,
        name: "Monday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 3,
        name: "Tuesday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 4,
        name: "Wednesday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 5,
        name: "Thursday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 6,
        name: "Friday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 7,
        name: "Saturday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
    ],
  },
  {
    id: 52,
    name: "Week 52",
    weekdays: [
      {
        id: 1,
        name: "Sunday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 2,
        name: "Monday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 3,
        name: "Tuesday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 4,
        name: "Wednesday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 5,
        name: "Thursday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 6,
        name: "Friday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
      {
        id: 7,
        name: "Saturday",
        schedule: [
          { id: 0, task: [] },
          { id: 1, task: [] },
          { id: 2, task: [] },
          { id: 3, task: [] },
          { id: 4, task: [] },
          { id: 5, task: [] },
          { id: 6, task: [] },
          { id: 7, task: [] },
          { id: 8, task: [] },
          { id: 9, task: [] },
          { id: 10, task: [] },
          { id: 11, task: [] },
          { id: 12, task: [] },
          { id: 13, task: [] },
          { id: 14, task: [] },
          { id: 15, task: [] },
          { id: 16, task: [] },
          { id: 17, task: [] },
          { id: 18, task: [] },
          { id: 19, task: [] },
          { id: 20, task: [] },
          { id: 21, task: [] },
          { id: 22, task: [] },
          { id: 23, task: [] },
          { id: 24, task: [] },
        ],
      },
    ],
  },
];
